### ISSUE TITLE
FR: add a metadata hook

### ISSUE THREAD

**Issue by ofek** [agoose77/hatch-nodejs-version#1]
https://hatch.pypa.io/dev/plugins/metadata-hook/reference/

I wanted make a PR to switch https://github.com/squidfunk/mkdocs-material/blob/master/setup.py

I could do a [custom](https://hatch.pypa.io/dev/plugins/metadata-hook/custom/) but this would fit nicely here 🙂

**Comment by agoose77** [comment]
@ofek thanks! Could you explain the motivation for this, i.e. what does a metadata hook do? :)

**Comment by ofek** [comment]
From OP: https://github.com/squidfunk/mkdocs-material/blob/7cb9d7b2b957cb64fee584e154005391c8ca0a63/setup.py#L42-L53

I was about to port it to Hatchling but realized it pulls many things from `package.json`

**Comment by agoose77** [comment]
@ofek 2d72fb825fa0bc6116bc67f70c2a7a283a0893bb adds this tentatively. Could you try it out with your repository?

**Comment by ofek** [comment]
Works! Try `python -m build` on https://github.com/ofek/mkdocs-material/tree/modernize-metadata

**Comment by agoose77** [comment]
Fab, that helped me catch a mistake on my part!

**Comment by agoose77** [comment]
See https://pypi.org/project/hatch-nodejs-version/0.2.1/!

**Comment by ofek** [comment]
Thanks!!!

**Comment by ofek** [comment]
😄 https://github.com/squidfunk/mkdocs-material/blob/master/pyproject.toml
