### ISSUE TITLE
0.3.0: missing git tag

### ISSUE THREAD

**Issue by kloczek** [agoose77/hatch-nodejs-version#14]
According to https://pypi.org/project/hatch-nodejs-version/ latest version is 0.3.0 however here there is no corresponding git tag.
Not pushed local git changes to github? 🤔

**Comment by agoose77** [comment]
Ah thanks! This was an oversight on my part during releasing. I've created a release from the appropriate commit!

**Comment by kloczek** [comment]
Thank you 👍 😄
